Vagrant.configure("2") do |config|
  config.vm.box = "generic/ubuntu1804"
  config.vm.provision "file", source: "empty_file", destination: "~/emptyfile"
  config.vm.provision "shell", path: "provision.sh"
end